AGENT_STATUS_IDLE = 0
AGENT_STATUS_PICKUP = 1
AGENT_STATUS_CARRY = 2
AGENT_STATUS_DROPOFF = 3

AGENT_ORIENTATION_NORTH = 0
AGENT_ORIENTATION_EAST = 1
AGENT_ORIENTATION_SOUTH = 2
AGENT_ORIENTATION_WEST = 3
AGENT_ORIENTATIONS = [
    AGENT_ORIENTATION_NORTH,
    AGENT_ORIENTATION_EAST,
    AGENT_ORIENTATION_SOUTH,
    AGENT_ORIENTATION_WEST,
]

SQUARE_SYMBOL_EMPTY = 0
SQUARE_SYMBOL_OCCUPIED = 1

SPAWN_BORDER = 1
SPAWN_OCCUPIED_CELLS_BORDER = 0

IDLING_NEIGHBORHOOD_SEARCH_RANGE = 2

DIRS = [(0, 1), (1, 0), (0, -1), (-1, 0)]  # N,E,S,W
DIR_NAMES = ["N", "E", "S", "W"]

MAPF_CONTROLLER_CENTRALIZED = "CENTRALIZED"
MAPF_CONTROLLER_DECENTRALIZED_TOKEN_PASSING = "DECENTRALIZED_TOKEN_PASSING"
MAPF_CONTROLLER_DECENTRALIZED_NEGOTIATE_EGOISTIC = "DECENTRALIZED_NEGOTIATE_EGOISTIC"
MAPF_CONTROLLER_DECENTRALIZED_NEGOTIATE_ALTRUISTIC = (
    "DECENTRALIZED_NEGOTIATE_ALTRUISTIC"
)
MAPF_CONTROLLER_DECENTRALIZED_NEGOTIATE_EGOISTIC2 = "DECENTRALIZED_NEGOTIATE_EGOISTIC2"
MAPF_CONTROLLER_DECENTRALIZED_NEGOTIATE_ALTRUISTIC2 = (
    "DECENTRALIZED_NEGOTIATE_ALTRUISTIC2"
)
MAPF_CONTROLLER_DECENTRALIZED_NEGOTIATE_KARMA = "DECENTRALIZED_NEGOTIATE_KARMA"
MAPF_CONTROLLER_DECENTRALIZED_NEGOTIATE_TRIP_KARMA = (
    "DECENTRALIZED_NEGOTIATE_TRIP_KARMA"
)
